# Generated by Django 5.1.1 on 2024-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0002_remove_category_task'),
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='task_category.category'),
        ),
    ]
