# Generated by Django 5.1.1 on 2024-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='file_path_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='float_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='json_field',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='uuid_field',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='file_field',
            field=models.FileField(upload_to=''),
        ),
    ]
