# Generated by Django 5.1.1 on 2024-11-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
    ]
